dependencies:
  services:
    redis:
      image: index.docker.io/sourcegraph/redis-cache:insiders
      ports:
      - 6379
      volumes:
        - ./dev/redis.conf:/etc/redis/redis.conf
        - redis_data:/data
    postgresql:
      image: index.docker.io/sourcegraph/postgres-12.6-alpine:insiders
      ports:
        - 5432
      environment:
        POSTGRES_PASSWORD: sourcegraph
        POSTGRES_USER: sourcegraph
        POSTGRES_DB: sourcegraph
        POSTGRES_INITDB_ARGS: --encoding=UTF8 
      volumes:
        # Match PGDATA in Dockerfile
        # https://sourcegraph.com/search?q=context:%40sourcegraph/all+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:%5Edocker-images/postgres.*/Dockerfile+PGDATA
        - postgres_12_data:/data/pgdata-12
  volumes:
    - redis_data
    - postgres_12_data
environment:
  DB_STARTUP_TIMEOUT: 60s
